### ISSUE TITLE
Sharp sky horizon line

### ISSUE THREAD

**Issue by MinersHavenM43** [m3t4f1v3/voxy#11]
![Image](https://github.com/user-attachments/assets/4009779e-6d05-4a04-b3ee-0fe2b71211a0)
The divide between the two shades of blue in the sky near the horizon should be blurred, but in the 1.20.1 and 1.21.1 backports the divide is sharp. This is fixed with Vanilla fog enabled but that causes its own issues. This does not occur in upstream Voxy, whether it be from Modrinth or compiled from source. This occurs the same way even with only Sodium, this Voxy fork and Fabric API.

**Comment by m3t4f1v3** [comment]
that might just be because of minecraft changes, i fixed this with smoothskies

**Comment by MinersHavenM43** [comment]
Nope, that mod didn't fix the issue no matter what settings I tried :/
I did end up fixing it though by changing these lines in `/src/main/java/me/cortex/voxy/client/mixin/minecraft/MixinFogRenderer.java`:
```java
RenderSystem.setShaderFogStart(999999999);
RenderSystem.setShaderFogEnd(999999999);
```
to
```java
RenderSystem.setShaderFogColor(1.0f, 1.0f, 1.0f, 0.0f);
```
There is most certainly a better solution than this as I barely know anything about Minecraft modding, but it works for now.

**Comment by m3t4f1v3** [comment]
that does some weird stuff with fog, eventually ill figure out how to cancel the fog entirely

**Comment by PGgamer2** [comment]
How about doing something similar to [Smooth Skies](https://codeberg.org/MicrocontrollersDev/Smooth-Skies/raw/branch/1.20/src/main/java/dev/microcontrollers/smoothskies/mixin/BackgroundRendererMixin.java)?
<details open>

```JAVA
package me.cortex.voxy.client.mixin.minecraft;

import com.llamalad7.mixinextras.injector.wrapmethod.WrapMethod;
import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;
import com.llamalad7.mixinextras.sugar.Local;
import me.cortex.voxy.client.config.VoxyConfig;
import me.cortex.voxy.client.core.IGetVoxyRenderSystem;
import net.minecraft.client.Camera;
import net.minecraft.client.Minecraft;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.renderer.FogRenderer;
import net.minecraft.client.renderer.FogRenderer.FogMode;
import net.minecraft.util.CubicSampler;
import net.minecraft.world.phys.Vec3;
import org.joml.Vector3f;
import org.joml.Vector3fc;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import com.mojang.blaze3d.systems.RenderSystem;

@Mixin(value = FogRenderer.class,remap = true)
public class MixinFogRenderer {
    @Unique
    private static boolean voxy$isVanillaFog() {
        var vrs = (IGetVoxyRenderSystem) Minecraft.getInstance().levelRenderer;
        return VoxyConfig.CONFIG.renderVanillaFog || vrs == null || vrs.getVoxyRenderSystem() == null;
    }

    @Inject(
        method = "setupFog(Lnet/minecraft/client/Camera;Lnet/minecraft/client/renderer/FogRenderer$FogMode;FZF)V",
        at = @At("TAIL"),
        cancellable = true
    )
    private static void voxy$overrideFog(
        Camera camera,
        FogMode fogMode,
        float viewDistance,
        boolean thickFog,
        float tickDelta,
        CallbackInfo ci
    ) {
        if (voxy$isVanillaFog()) {
            RenderSystem.setShaderFogEnd(viewDistance);
        } else {
            RenderSystem.setShaderFogStart(999999999);
            RenderSystem.setShaderFogEnd(999999999);
        }
    }

    @WrapOperation(method = "setupColor", at = @At(value = "INVOKE", target = "Lnet/minecraft/util/CubicSampler;gaussianSampleVec3(Lnet/minecraft/world/phys/Vec3;Lnet/minecraft/util/CubicSampler$Vec3Fetcher;)Lnet/minecraft/world/phys/Vec3;"))
    private static Vec3 voxy$onSampleColor(Vec3 i, CubicSampler.Vec3Fetcher j, Operation<Vec3> original, @Local(argsOnly = true) ClientLevel level, @Local(ordinal = 0) Vec3 vec3) {

        return !voxy$isVanillaFog() && level.dimensionType().hasSkyLight() ? vec3 : original.call(i, j);
    }

    @WrapOperation(method = "setupColor", at = @At(value = "INVOKE", target = "Lorg/joml/Vector3f;dot(Lorg/joml/Vector3fc;)F"))
    private static float voxy$afterVectorDot(Vector3f instance, Vector3fc v, Operation<Float> original) {
        return voxy$isVanillaFog() ? original.call(instance, v) : 0F;
    }

    @WrapOperation(method = "setupColor", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/multiplayer/ClientLevel;getRainLevel(F)F"))
    private static float voxy$setRainLevel(ClientLevel instance, float v, Operation<Float> original) {
        return voxy$isVanillaFog() ? original.call(instance, v) : 0F;
    }

    @WrapOperation(method = "setupColor", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/multiplayer/ClientLevel;getThunderLevel(F)F"))
    private static float voxy$setThunderLevel(ClientLevel instance, float v, Operation<Float> original) {
        return voxy$isVanillaFog() ? original.call(instance, v) : 0F;
    }
}
```

</details>

**Comment by m3t4f1v3** [comment]
ill add smth similar to an eventual branch where i mess about

**Comment by ruvaldak** [comment]
i too would love to see a backport of the environmental fog available in current voxy versions. it really helps add depth to the scene.

**Comment by m3t4f1v3** [comment]
env fog is a new minecraft thing afaik

**Comment by HySand** [comment]
blindness don't work either

**Comment by m3t4f1v3** [comment]
you can try disabling the mixin if you need blindness to work

**Comment by m3t4f1v3** [comment]
fixed by https://github.com/m3t4f1v3/voxy/pull/145
